mysql:
  domain: analytics.db.svc.eqiad.wmflabs
  # TODO: remove this when the multiinstance replica proxy is removed
  host: enwiki.analytics.db.svc.eqiad.wmflabs
dbProxy: 
  image:
    tag: latest
jupyterhub:
  hub:
    db:
      type: mysql
      upgrade: true
  ingress: 
    enabled: true
    hosts:
    - hub.paws.wmcloud.org
# So that we don't use the Bitnami charts in Cloud VPS deployment
localdev:
  enabled: false
